### ISSUE TITLE
Reduce duration of `MADMMplasso()` example

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/MADMMplasso#15]
On some CRAN-like machines, which are usually slower than typical PCs, the example for the `MADMMplasso()` function take too long (i.e., more than 5 seconds) to run. Elapsed time is often timed at 12 seconds or more. This will probably be an issue for CRAN reviewers, so it should be addressed before submitting.

**Comment by wleoncio** [comment]
This may get solved once #17 is resolved, but any work on speeding up the example (or reducing its footprint, as it is currently almost 100 LOC long) is welcome.

**Comment by Theo-qua** [comment]
Sure, Waldir. I will look into this. 


Theo
Theophilus Quachie Asenso, PhDPost-doctoral research fellowUniversity of Oslo, Norway+4797358955 

    On Friday, January 12, 2024 at 09:49:31 AM GMT+1, Waldir Leoncio ***@***.***> wrote:  
 
 


This may get solved once #17 is resolved, but any work on speeding up the example (or reducing its footprint, as it is currently almost 100 LOC long) is welcome.
