### ISSUE TITLE
Translation to C++

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/MADMMplasso#2]
Hi @Theo-qua,

Could you please confirm if the function to be translated is the one highlighted on the link below?

https://github.com/ocbe-uio/MADMMplasso/blob/92b770d7f0165b3f4b5224539af5e1f49d812b06/R/MADAMM11.R#L1C4-L620

I'll be happy to help you with the translation. Before I start, though, it would be very useful if you could send me one or more examples of direct usage of that function, with inputs and expected outputs, so I can make sure functionality is maintained.

Best,
Waldir

**Comment by Theo-qua** [comment]
Dear Waldir,
Yes, that is the correct function. Please find attached the script for the example. I have included some functions that are called in the main function just to avoid any errors. Thank you for agreeing to help. 

Best regards,Theo




 

    On Thursday, June 22, 2023 at 02:13:13 PM GMT+2, Waldir Leoncio ***@***.***> wrote:  
 
 


Hi @Theo-qua,

Could you please confirm if the function to be translated is the one highlighted on the link below?

https://github.com/ocbe-uio/MADMMplasso/blob/92b770d7f0165b3f4b5224539af5e1f49d812b06/R/MADAMM11.R#L1C4-L620

I'll be happy to help you with the translation. Before I start, though, it would be very useful if you could send me one or more examples of direct usage of that function, with inputs and expected outputs, so I can make sure functionality is maintained.

Best,
Waldir

**Comment by wleoncio** [comment]
Hi Theo,

Could you please send the files directly to my uio address? If you simply reply to this GitHub thread, it will drop the attachment.

Thanks,
Waldir

**Comment by wleoncio** [comment]
Hi @Theo-qua,

Just an update on this issue: the function has been completely translated. Now I need to spend some time debugging, since some elements in the output (particularly those related to beta) are not being properly calculated.

In any case, you can take the new function for a spin by installing it from the `issue-2` branch:

```r
remotes::install_github("ocbe-uio/MADMMplasso@issue-2")
```

**Comment by Theo-qua** [comment]
Hello Waldir,
Thank you for the update. I will check this out right away. Please let me know if there is anything to be done from my end.

**Comment by wleoncio** [comment]
> Please let me know if there is anything to be done from my end.

Perhaps we can set up a meeting after you look at the C++ code to let me know if you have any questions regarding it? It would be nice to have another set of eyes on it to see if we can spot where the issue is.

I might also start doing some optimization to simplify the function. There's a bit of duplicated code over there that, once simplified, could help with debugging.

**Comment by Theo-qua** [comment]
This sounds good.

**Comment by Theo-qua** [comment]
Hello Waldir, 
I have been able to go through the  C++ code. That's quite a huge work you've done there. I just have some few questions to ask concerning  a few lines. Could you please schedule a short meeting tomorrow (I think 10-20 minutes will do) to discuss this. Thank you once again.
