### ISSUE TITLE
Check the legacy in the current setting

### ISSUE THREAD

**Issue by Theo-qua** [ocbe-uio/MADMMplasso#27]
I have been trying the current version with legacy = TRUE but I get the following error

Error in MADMMplasso(X, Z, y, alpha = alpha, my_lambda = NULL, lambda_min = 0.001,  : 
  unused argument (legacy = F)

It runs normal when I load the function to my local computer so I cannot figure out what is causing the online version to give me error.

**Comment by wleoncio** [comment]
Hi Theo,

Could you share an example script so I can reproduce the error? At least the `MADMMplasso()` example runs fine, even when swtiching `legacy` to `TRUE`.

**Comment by wleoncio** [comment]
Also, please confirm which version of the package you're using with `packageVersion("MADMMplasso")`.

**Comment by Theo-qua** [comment]
I installed the version 0.0.0.9011 

I copied the same example from the github but included legacy in the call as bellow 

fit <- MADMMplasso( X, Z, y, alpha=alpha, my_lambda=NULL, lambda_min=0.001, max_it=5000, e.abs=e.abs, e.rel=e.rel, maxgrid=nlambda, nlambda=nlambda, rho=5, tree=TT, my_print=FALSE, alph=1, parallel=FALSE, pal=1, gg=gg1, tol=tol,legacy=TRUE  )


Maybe there is something I am missing.

**Comment by Theo-qua** [comment]
I will check why this is happening at my end. It runs normal when I load the package functions into R so it could  be a problem with the installation from github at my end. 


I will keep you updated. Thank you 


Theo

**Comment by wleoncio** [comment]
Maybe it helps to add `force = TRUE` on your call to `install_github()` to make surey you're getting the latest version.

**Comment by Theo-qua** [comment]
![Screenshot 2024-02-21 at 12 13 31](https://github.com/ocbe-uio/MADMMplasso/assets/85598983/a88b6e25-9a38-4633-8bec-5769d08895ea)

**Comment by wleoncio** [comment]
Please do the same but without the `system.time()` wrap, which is masking the results from `traceback()`.

In any case, there seems to be something strange with the version of `MADMMplasso()` that you're running there, because it does not contain a `legacy` parameter (that is what the error is complaining about). Please make sure you don't have another function of the same name in your environment. If you do, it will be called instead of the one in the package.

**Comment by Theo-qua** [comment]
You are right. It seem to calling my old function which does not contain legacy. I restarted my R but was still getting error so I decided to clear the memory. It now working. Thank you for the assistance. 



Theo

**Comment by Theo-qua** [comment]
I am closing this issue
