### ISSUE TITLE
`MADMMplasso()` fails for parallel = TRUE

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/MADMMplasso#33]
Running [testthat/test-MADMMplasso.R](https://github.com/ocbe-uio/MADMMplasso/blob/2b4d2674959dc5d236ad0d6907baca611ae7d117/tests/testthat/test-MADMMplasso.R) works as-is, but if the `MADMMplasso()` calls are set to use `parallel = TRUE`, they fail. Also, if `parallel = FALSE` and `pal = FALSE`, the C++ code fails (no problems if `legacy = TRUE`).

I assume `parallel = TRUE` should work for whatever value of `pal`, and also that this was working at some point in the past, so I'll start by identifying the last commit on `main` where this broke so we can take it from there.

**Comment by Theo-qua** [comment]
If parallel = FALSE and pal should be  TRUE. pal is a switch between the usual loop and any other like parallel and lapply. Once pal is TRUE, the usual loop will be used.  





Theophilus Quachie Asenso, PhDPost-doctoral research fellowUniversity of Oslo, Norway+4797358955 

    On Monday, March 4, 2024 at 05:09:29 PM GMT+1, Waldir Leoncio ***@***.***> wrote:  
 
 


Runnning testthat/test-MADMMplasso.R works as-is, but if the MADMMplasso() calls are set to use parallel = TRUE, they fail. Also, if parallel = FALSE and pal = FALSE, the C++ code fails (no problems if legacy = TRUE).

I assume parallel = TRUE should work for whatever value of pal, and also that this was working at some point in the past, so I'll start by identifying the last commit on main where this broke so we can take it from there.

**Comment by wleoncio** [comment]
I'm a bit confused, which combinations of `parallel` and `pal` should be allowed, then?

`parallel` | `pal` | allowed?
----------|------------|-----------
`FALSE` | `FALSE` | ?
`FALSE` | `TRUE` | ?
`TRUE` | `FALSE` | ?
`TRUE` | `TRUE` | ?

**Comment by wleoncio** [comment]
OK, so all combinations are valid?

**Comment by wleoncio** [comment]
Thanks for the clarification. And what if the user calls `MADMMplasso()` with both `parallel` and `pal` set to `TRUE`?

**Comment by Theo-qua** [comment]
We should create a warning for this. I actually had not thought about that. I included in the documentation that if parallel is TRUE, pal should be FALSE but maybe that is not enough

**Comment by wleoncio** [comment]
Yeah, a warning sounds good, perhaps an error should be more appropriate. So the updated reference table:

`parallel` | `pal` | behavior
----------|------------|-----------
`FALSE` | `FALSE` | Use `lapply()`
`FALSE` | `TRUE` | Use loop
`TRUE` | `FALSE` | Use parallel
`TRUE` | `TRUE` | Not allowed. Throw `warning()` or `error()`

**Comment by Theo-qua** [comment]
Yes, you are right

**Comment by wleoncio** [comment]
Once #44 is merged, this will no longer be an issue for `legacy` (R). For `!legacy` (C++), using `parallel = TRUE` does not look reliable (some out-of-bounds errors may happen, e.g. [this example gist](https://gist.github.com/wleoncio/0318b15226128e6aef7898d4a2c009e9)). Two ways to move forward to close this issue:

1. Fix the C++ behavior
2. Temporarily drop `parallel = TRUE` for `legacy = FALSE`

Following option 1, I think the problem may be in the assignments below: 
https://github.com/ocbe-uio/MADMMplasso/blob/20769e1706c065d2be033e12470b4321b3e4194e/src/hh_nlambda_loop_cpp.cpp#L68-L77

**Comment by wleoncio** [comment]
No longer an issue, working as of 0.0.0.9019.

**Comment by Theo-qua** [comment]
I have a question. How will the user use the default with parallel=FALSE and pal=FALSE. This will be possible only when cl is not greater than or equal to1. If cl==1, pal=TRUE and parallel=FALSE from what I can see. Also when cl>1, parallel=TRUE and pal=FALSE. Meaning the default cl should be 0? We need to be careful with this aspect of the input. 
Please let me know what you think. Thank youBest regards,Theo
Theophilus Quachie Asenso, PhDPost-doctoral research fellowUniversity of Oslo, Norway+4797358955 

    On Tuesday, July 30, 2024 at 02:00:31 PM GMT+2, Waldir Leoncio ***@***.***> wrote:  
 
 


No longer an issue, working as of 0.0.0.9019.

**Comment by Theo-qua** [comment]
Hello Waldir,I get your explanation. I think I made a mistake in my first email. I was referring to a situation where parallel=FALSE and pal=FALSE. This should not be the default though. The default  should be parallel=FALSE and pal=TRUE. This allows any user to use the package with or without parallel computing environment. 
 The case for parallel=FALSE and pal=FALSE is the lapply function and I was only saying that we need to make room for this situation. This situation will only be possible in the current setting when cl=0 or any any value less than 1. 

Best regards,Theo


Theophilus Quachie Asenso, PhDPost-doctoral research fellowUniversity of Oslo, Norway+4797358955 

    On Tuesday, July 30, 2024 at 02:27:22 PM GMT+2, Waldir Leoncio ***@***.***> wrote:  
 
 


Hi Theo,

IIRC the default used to be parallel = TRUE, pal = FALSE, right? If so, that has been preserved, at least in multithreaded machines. If we want the default to be FALSE-FALSE we do need to set cl = 1L as the default, as you mentioned. Let me know if that's your preference.

**Comment by wleoncio** [comment]
> The default  should be parallel=FALSE and pal=TRUE.

OK, in that case I'll open an issue to address this.

**Comment by wleoncio** [comment]
> The case for parallel=FALSE and pal=FALSE is the lapply function and I was only saying that we need to make room for this situation. This situation will only be possible in the current setting when cl=0 or any any value less than 1.

On the current implementation, `cl = 1` corresponds to `parallel=FALSE`. In other words, if the user wants `parallel = FALSE, pal = FALSE` they need to set `cl = 1, pal = FALSE`. No need to do `cl = 0` (I think the user should not even be allowed to put non-positive values there).

**Comment by Theo-qua** [comment]
Yes, I agree with you. So the only change will now be in the documentation of "pal". 



Theophilus Quachie Asenso, PhDPost-doctoral research fellowUniversity of Oslo, Norway+4797358955 

    On Tuesday, July 30, 2024 at 03:28:03 PM GMT+2, Waldir Leoncio ***@***.***> wrote:  
 
 



The case for parallel=FALSE and pal=FALSE is the lapply function and I was only saying that we need to make room for this situation. This situation will only be possible in the current setting when cl=0 or any any value less than 1.


On the current implementation, cl = 1 corresponds to parallel=FALSE. In other words, if the user wants parallel = FALSE, pal = FALSE they need to set cl = 1, pal = FALSE. No need to do cl = 0 (I think the user should not even be allowed to put non-positive values there).
