### ISSUE TITLE
cv_MADMMplasso return an error

### ISSUE THREAD

**Issue by Theo-qua** [ocbe-uio/MADMMplasso#35]
Hello Waldir, 
Could you please check the hh_nlambda_loop call. It seems not be working for the cv_MADMMplasso function. I get this error 

Error in hh_nlambda_loop_cpp(lam, nlambda, beta0, theta0, beta, beta_hat,  : 
  object '_MADMMplasso_hh_nlambda_loop_cpp' not found

The was not error with the MADMMplasso call though. 

You can try with the example on the readme. 

Best regards,
Theo

**Comment by wleoncio** [comment]
Hi Theo,

I'm afraid I can't reproduce the issue, it runs fine here. Please find the code I ran (adapted from README) and its output in the link below. Remember to clean your environment of competing objects―`rm(list = ls())`―and make sure you're using the latest version of the package before proceeding.

https://gist.github.com/wleoncio/ff34e3c1dc95f94d153469b4e92ea532

Do you still run into the issue after running the code from the link above?

**Comment by wleoncio** [comment]
Can do
