### ISSUE TITLE
Replace `parallel` with `cl`?

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/MADMMplasso#40]
I might well be missing something here, but does `MADMMplasso()` need to have both a `parallel` and a `cl` argument? I mean, if `cl == 1` isn't it by definition equivalent to `parallel == FALSE` and `cl > 1L` equivalent to `parallel == TRUE`?

**Comment by Theo-qua** [comment]
cl is to specify the number of the CPUs. So it is different from parallel

**Comment by wleoncio** [comment]
Right, but does it make sense to have `parallel = TRUE` and `cl = 1`? Likewise, does it make sense to set `parallel = FALSE` and `cl > 1`?

**Comment by wleoncio** [comment]
OK, so that's my point, I don't see the need for a `parallel` argument since it can be indirectly defined through `cl`. Having both, we are allowing the user to call the senseless combinations I mentioned above.
