### ISSUE TITLE
On issue-17 branch: `plot()` of `MADMMplasso(legacy=FALSE)` object fails

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/MADMMplasso#42]
To reproduce, run the code from the gist below:

https://gist.github.com/wleoncio/c1658302683fb872595749d386fe00af

Running `plot(fit_R)` should produce a plot, but `plot(fit_C)` fails. The cleanest solution may be to modify `MADMMplasso()` so that `loop_output` always has the same structure (i.e., regardless of whether `legacy` is TRUE or FALSE).

**Comment by wleoncio** [comment]
Note this is fine on the main branch, so replacing 

```r
remotes::install_github("ocbe-uio/MADMMplasso@issue-17")
```

with 

```r
remotes::install_github("ocbe-uio/MADMMplasso")
```

Makes `plot(fit_C)` work. This is because the version on main still has C code that uses lots of lists, which was slowing down the code.

**Comment by wleoncio** [comment]
Hi Theo,

Can you confirm that version 0.0.0.9017-1719322643 (on the issue-17 branch) fixes the plotting issue on C++?

**Comment by Theo-qua** [comment]
Dear Waldir,I did not see this message. My apologies for responding late. 
I can confirm that the plotting issue has now been fixed.


Best regards,Theo




Theophilus Quachie Asenso, PhDPost-doctoral research fellowUniversity of Oslo, Norway+4797358955 

    On Tuesday, June 25, 2024 at 03:38:41 PM GMT+2, Waldir Leoncio ***@***.***> wrote:  
 
 


Hi Theo,

Can you confirm that version 0.0.0.9017-1719322643 (on the issue-17 branch) fixes the plotting issue on C++?
