### ISSUE TITLE
Restrict condition to only when my_lambda = NULL

### ISSUE THREAD

**Issue by Theo-qua** [ocbe-uio/MADMMplasso#57]
Hello Waldir,
Now the plots function works for both the R and C++. 

I tried the cv_MADMMplasso but had a problem because the new line we have included; 

# Validation
  stopifnot(nlambda <= maxgrid)

The cv_MADMMplasso does not need maxgrid so I think the condition should placed inside 

if (is.null(my_lambda)) 

With this, the MADMMplasso call in the cv_MADMMplasso will not use maxgrid but the following; 
} else {
    lambda_i <- my_lambda
    gg1 <- gg
    gg <- gg1
  }

Best regards,
Theo

**Comment by wleoncio** [comment]
Hi Theo,

Thanks for testing and reporting. I'm trying to wrap my head around your, but what I'm thinking right now is that if `maxgrid` is not used by `cv_MADMMplasso()`, then it should be made an optional argument, ideally by giving it a default value. Assuming `nlambda` is a mandatory argument, perhaps we can default to `maxgrid = nlambda`?

**Comment by Theo-qua** [comment]
I think we can move the line "stopifnot(nlambda <= maxgrid)" from the current position into "if (is.null(my_lambda))". This should solve the problem.

**Comment by wleoncio** [comment]
OK, will do.

**Comment by Theo-qua** [comment]
I have just finished going through everything, including setting cl>1 and the results are now good with no error messages. I also can tell that the C++ performs quite well with cl=4. 


Best regards,Theo




 

    On Tuesday, September 3, 2024 at 06:50:18 AM GMT+2, Waldir Leoncio ***@***.***> wrote:  
 
 


OK, will do.

**Comment by wleoncio** [comment]
Wonderful to hear! :)
