### ISSUE TITLE
Some examples yield errors

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/MADMMplasso#6]
# How to reproduce

Run `devtools::run_examples()` from the package root.

# First error detected

Error seems to happen in the example for `cv.MADMMplasso()`:

> Error in yh[, , ii] <- (n_i) :
> number of items to replace is not a multiple of replacement length

In other words, there is a mismatch between the length of `n_i` and `yh[, , ii]`.

**Comment by Theo-qua** [comment]
I realized this error last night. I think it came from a recent update I did. I will check it. thank you for the information.

**Comment by wleoncio** [comment]
Thank you for the initiative. I'll assign the issue to you, then. Please let me know if there's anything I can help with here.

**Comment by Theo-qua** [comment]
Hello Waldir,
I have fixed the  problem on test error in the package. The check also ended with 0 errors, 3 warnings and  3 notes and these are related to the documentation.

**Comment by wleoncio** [comment]
Wonderful, thanks for the very quick action. I can confirm this fixes the issue. I'll take care of merging these changes into my PR (#4) and resolve the remaining issues. Also, marking this issue as resolved.
