### ISSUE TITLE
Reduce example length

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/MADMMplasso#7]
A run of `devtools::check()` detects these two very long examples:

![bilde](https://github.com/ocbe-uio/MADMMplasso/assets/8234768/7f3f8375-8f0b-4f92-b479-079cdc44de11)

For a faster package development process (not to mention a CRAN release), it would be great if these examples were reduced to run in no more than 5 seconds. The full example already coded does look useful, so maybe they should be part of a package demo or vignette?

Translating `MADMMplasso()` to C++ (see issue #2) should help reduce the computing time for `MADMMplasso()`, but unlikely by the 70x factor necessary to decrease the CPU time enough.

**Comment by wleoncio** [comment]
I couldn't get the `MADMMplasso()` example to run with `nlambda <- 1`, but I did manage to run it with `nlambda <- 2` as long as the function is called with `maxgrid = nlambda`. Does that make sense?

**Comment by Theo-qua** [comment]
Yes, it makes sense. To run with nlambda=1, set  my_lambda=c(rep(0.2,dim(y)[2])) and maxgrid = nlambda. NB: 0.2 is arbitrary. 

If my_lambda=NULL, you need nlambda>1

I got the following with nlambda=1 

"Convergence reached after  iterations"
[2] "38"                                   
Time difference of 2.455389 secs
[1]  1.000000 14.000000 31.000000  1.403844

**Comment by wleoncio** [comment]
Interesting, over here `nlambda=1` will break on this part:

https://github.com/ocbe-uio/MADMMplasso/blob/main/R/MADAMM11.R#L1098-L1104

Which happens because `lam` is a vector, so the two-dimensional `lambda=lam[hh,]` assignment doesn't work.

The example runs fast enough for `nlambda=2`, so maybe we should stick with that solution for now? We can investigate any eventual bug related to using `nlambda=1` on a separate issue.

**Comment by Theo-qua** [comment]
You are right. It should have been my_lambda=matrix(rep(0.2,dim(y)[2]),1). I made a typo in my previous message. 

fit<-MADMMplasso(X,Z,y,alpha=alpha,my_lambda=matrix(rep(0.2,dim(y)[2]),1),lambda_min=0.001,max_it=5000,e.abs=e.abs,e.rel=e.rel,maxgrid=1,nlambda = nlambda, rho=5,tree = TT,my_print = FALSE,alph=1,parallel =FALSE,pal=1,gg=gg1,tol=tol,cl=6)

[1] "Convergence reached after  iterations"
[2] "38"                                   
Time difference of 2.455389 secs
[1]  1.000000 14.000000 31.000000  1.403844

**Comment by wleoncio** [comment]
OK, that's progress! Now `MADMMplasso()` works, but the `plot()` method fails [here](https://github.com/ocbe-uio/MADMMplasso/blob/main/R/MADAMM11.R#L2260) because `my_beta` is a 1-dim vector (so `apply()` doesn't work).

Are we running the same package version, 0.0.0.9002 from the main branch?

**Comment by Theo-qua** [comment]
Yes, the plot is not meant for a single lambda so it will not work. That is not an issue because the plot is to show how the variables are selected along a given lambda values. With a single lambda, there will be no need for a plot. 

I am using the same version 0.0.0.9002

**Comment by wleoncio** [comment]
Alright. Anyway, I fixed the plot issue by changing `my_beta <- as.matrix(my_beta1[, , ii])`, which should have no negative side-effects. Incoming PR for review. :)

**Comment by wleoncio** [comment]
> With a single lambda, there will be no need for a plot.

Sorry, Theo, I failed to take this part into consideration when coding. 🤦🏽‍♂️  Should the `plot()` method fail for single lambdas or is the proposed solution (plotting it anyway) acceptable?
